version: "3.9"

services:
  app:
    restart: always
    container_name: studyapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
